version: '2'
services:
    pesdoamendoim-app:
        image: pesdoamendoim
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://pesdoamendoim-postgresql:5432/PESdoAmendoim
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pesdoamendoim-postgresql:
        extends:
            file: postgresql.yml
            service: pesdoamendoim-postgresql
